# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/my_gantt',
                'doc_host': 'https://nmaghel-arch.github.io',
                'git_url': 'https://github.com/nmaghel-arch/my_gantt',
                'lib_path': 'my_gantt'},
  'syms': {'my_gantt.core': {'my_gantt.core.foo': ('core.html#foo', 'my_gantt/core.py')}}}
